### ISSUE TITLE
Write Docs & Publish Package in Hex.pm

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#10]
This project is *almost* ready to ship.
There are a few issues open to discuss but we can already *use* it in our app.
In order to do that we should:
+ [x] write docs to help ourselves and others “consume” the package
+ [x] re-do/update the instructions for getting the API tokens: 
https://github.com/dwyl/hapi-auth-google/blob/master/GOOGLE-APP-STEP-BY-STEP-GUIDE.md
+ [x] publish the package to hex.pm
+ [x] Add hex.pm badge using https://shields.io 

![image](https://user-images.githubusercontent.com/194400/69717865-cf14a700-1104-11ea-9f6b-8a361c5044ea.png)

```
![Hex.pm](https://img.shields.io/hexpm/v/elixir_auth_google?color=brightgreen&style=flat-square)
```
![Hex.pm](https://img.shields.io/hexpm/v/elixir_auth_google?color=brightgreen&style=flat-square)

**Comment by nelsonic** [comment]
I've spent the evening re-reading Google OAuth docs and writing #11 ... 📝 
I have 15 screenshots to annotate and write up the instructions. 🖼 
going to continue working on it tomorrow morning. 😪

**Comment by nelsonic** [comment]
When setting up a New Project so that we can use Google OAuth we see the following screen
informing us that "You don’t have any APIs available to use yet. To get started, click “Enable APIs and services” or go to the API library":

![elixir-auth-demo-enable-apis](https://user-images.githubusercontent.com/194400/69723299-24ef4c00-1111-11ea-8fb2-908c220d5d0c.png)

Clicking on the (ALL CAPS) **+ ENABLE APIS AND SERVICES** button takes us to the API landing page.
263 APIs and no "most popular/used" to help a beginner filter for what they are looking for ...
![image](https://user-images.githubusercontent.com/194400/69723540-bced3580-1111-11ea-818f-c4e5faf8f02d.png)

Is Google Maps API _really_ the one that should be at the top? 
**`Maybe`** it _is_ the most popular Google Service that devs integrate with ... 💭 

Why is this still available without a deprecation warning?! Come on Google! 😞 
![image](https://user-images.githubusercontent.com/194400/69723692-240aea00-1112-11ea-92c9-e8f149f2791b.png)

Searching for **`auth`** returns 6 results; none of which are relevant to Google Auth ...
![image](https://user-images.githubusercontent.com/194400/69724165-36d1ee80-1113-11ea-85f2-fbe994881616.png)

The last one "Identity and Access Management (IAM) API" _looks_ like it could be relevant ...
![image](https://user-images.githubusercontent.com/194400/69724243-6d0f6e00-1113-11ea-955a-53e1b4883042.png)

But it's actually for managing the users of Google Cloud Platform (GCP) and nothing to do with letting people authenticate with their Google Account ... 🤦‍♂ 

I get the feeling this is a red herring ... https://en.wikipedia.org/wiki/Red_herring

**Comment by SimonLab** [comment]
@nelsonic I was also confused on the APIs section, especially that at the moment we only want to get the basic user information and seems overkilling to enable an API for that. I manage to find the endpoint to get this information (see #9) after finding a similar issue on the nodejs google client repo: https://github.com/googleapis/google-api-nodejs-client/issues/1529

The endpoint `https://www.googleapis.com/oauth2/v3/userinfo?access_token=...` works without the need to enable any API but I was surprised to not be able to find a short documentation describing how to get this user profile information.

**Comment by nelsonic** [comment]
Select **Credentials** from the left side menu:
<img width="959" alt="elixir-auth-google-click-credentials-menu" src="https://user-images.githubusercontent.com/194400/69725448-1d7e7180-1116-11ea-9cfc-a4fc1e10030d.png">



Once in the credentials menu, click the **Create Credentials** button:
<img width="960" alt="Screenshot 2019-11-26 at 23 24 28" src="https://user-images.githubusercontent.com/194400/69725288-b2cd3600-1115-11ea-9601-04054cac6f5b.png">
That will popup a menu from which you will select **OAuth Client ID**. 

First set a product name ... Configure consent screen ... 
<img width="960" alt="elixir-auth-google-create-client-id-first-select-name" src="https://user-images.githubusercontent.com/194400/69727148-dabe9880-1119-11ea-923a-b366421b9f4b.png">

Why didn't they just have a logically flowing "wizard" that goes through the steps in the right order?!

**Comment by nelsonic** [comment]
The order it _should_ be done in:
<hr />

After creating the New Project,
the UI will return to the APIs dashboard
and the name of your app will appear in the top menu.

Click the **OAuth Consent Screen** from the left side menu:

<img width="959" alt="elixir-auth-google-consent-screen" src="https://user-images.githubusercontent.com/194400/69727668-e78fbc00-111a-11ea-8b39-124a4b045b02.png">

Upload an image if you have one (_e.g: the icon/logo for your app_):

<img width="1226" alt="OAuth-consent-screen-1of2" src="https://user-images.githubusercontent.com/194400/69727443-76500900-111a-11ea-9425-bff972afe565.png">

Scroll down to the bottom and click "**Save**":
<img width="1277" alt="OAuth-consent-screen-2of2" src="https://user-images.githubusercontent.com/194400/69727445-76e89f80-111a-11ea-860d-fd41939dd10f.png">

This will take you to the API Credentials page.
Click the **Create Credentials** button:
<img width="960" alt="Screenshot 2019-11-26 at 23 24 28" src="https://user-images.githubusercontent.com/194400/69725288-b2cd3600-1115-11ea-9601-04054cac6f5b.png">
That will popup a menu from which you will select **OAuth Client ID**.

**Comment by SimonLab** [comment]
@nelsonic when adding the redirect url, don't foget to use the enter key otherwise the url won't be saved. This one is quiet bad and you could spend a lot of time trying to figure out what's going on.
see https://github.com/dwyl/elixir-auth-google/issues/2#issuecomment-555525628

**Comment by nelsonic** [comment]
@SimonLab noted. Thanks for the reminder. 
I think it saved first time for me, but it's worth informing others in the docs. 👍 

<img width="970" alt="elixir-auth-google-oauth-client-credentials" src="https://user-images.githubusercontent.com/194400/69730648-5cb1c000-1120-11ea-8ad4-0ef62cfb6a0a.png">

> ⚠️ Don't worry, these keys aren't valid (_anymore_).
We deleted them _immediately_ after capturing the screenshot to avoid any security issues.
Obviously treat your credentials like you would the username+password for your bank account;
never share a **real** Client ID or secret on GitHub or any other public/insecure forum!

**Comment by nelsonic** [comment]
I've added all the `@doc` comments to the code so hex docs can be produced. ✅ 
I still need to finish documenting how to setup an app and linking to sample code.
But I was thinking of publishing a pre 1.0 version to Hex.pm just so that we can run it in the MVP.
Any objections?

**Comment by nelsonic** [comment]
Docs:

![image](https://user-images.githubusercontent.com/194400/69888893-363d8180-12e6-11ea-8c81-1df75329575b.png)

I feel these docs are _adequate_ for our purposes now. We will be supplementing them with more extensive code samples (_links to actual code in our MVP App_) shortly. 👍

**Comment by nelsonic** [comment]
Published alpha version to use in MVP: (_The fruits of @SimonLab's hard work!_) 🎉 
https://hex.pm/packages/elixir_auth_google/0.0.1
https://hexdocs.pm/elixir_auth_google/0.0.1

Will finish/update docs with code samples and re-publish 1.0 version shortly. ⏳

**Comment by nelsonic** [comment]
I'm busy refining the Docs of _this_ package by working on the Auth PR: https://github.com/dwyl/app-mvp-phoenix/pull/24
Once that is done we will have _sample_ code that we can include _here_.
# `continue`: https://github.com/dwyl/elixir-auth-google/pull/11

**Comment by nelsonic** [comment]
Demo version shipped to Heroku: https://elixir-auth-google-demo.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/70205869-7d2fda80-171d-11ea-98b3-6d4cd70f6393.png)

Docs complete!

**Comment by nelsonic** [comment]
https://hex.pm/packages/elixir_auth_google done. ✅
