### ISSUE TITLE
Codecov: Add Test Coverage Tracking

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#14]
In our pursuit of being a ["High Performing Technology Org"](https://github.com/nelsonic/nelsonic.github.io/issues/758), we need to track test coverage in all our code.
So that we know when code is tested (_or not_) and can improve maintainability/reliability. 

# Todo

+ [x] Add `{:excoveralls, "~> 0.7.0", only: [:test, :dev]},` to **`deps`** in **`mix.exs`**
+ [x] Add `cover: ["coveralls.json"],  "cover.html": ["coveralls.html"]` to `aliases` section
+ [x] `test_coverage` entry in `project` section. see:
see: https://github.com/dwyl/phoenix-chat-example/blob/89d5d1127bafdcb9493c5dab060c291aa296f5e2/mix.exs#L14
+ [x] add codecov script to https://github.com/dwyl/elixir-auth-google/blob/master/.github/workflows/elixir.yml#L20

Examples we can follow:
+ https://github.com/dwyl/learn-elixir/tree/master/codecov_example
+ https://github.com/dwyl/phoenix-chat-example/blob/master/mix.exs
+ https://github.com/dwyl/phoenix-ecto-encryption-example/blob/master/mix.exs

**Comment by nelsonic** [comment]
Relevant recent example: https://github.com/dwyl/fields/pull/51/files

**Comment by nelsonic** [comment]
@SimonLab I'm having a bit of trouble getting the Codecov upload script to work, see: https://github.com/dwyl/elixir-auth-google/pull/11https://github.com/dwyl/elixir-auth-google/pull/11#issuecomment-559621873
Coverage works on `localhost` and on GitHub CI. 
The only thing that is failing is uploading the coverage report to Codecov.io 

And worryingly, even though the upload _fails_, GitHub action reports _success_ ... 😕 
https://github.com/dwyl/elixir-auth-google/commit/82d1d1f82be4a5509d050a03739e7a0542670c0c/checks?check_suite_id=334000821
![image](https://user-images.githubusercontent.com/194400/69836569-afcf6400-1241-11ea-933e-9f73a827677a.png)

**Comment by SimonLab** [comment]
I'm going to check the instruction on https://github.com/codecov/codecov-action as you did to see if we missed something but if it's still not working after that we can then switch to Travis!

**Comment by SimonLab** [comment]
`curl` should be accessible in the github actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

I think this is an issue with codecov-action.
switching to Travis!

**Comment by nelsonic** [comment]
Thanks @SimonLab 👍
