### ISSUE TITLE
Handle Auth Failure Conditions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#16]
As a person using the @dwyl app to be more personally effective,
I do not want to stumble at the first hurdle trying to authenticate.
I don't _expect_ to see unfriendly/unrecoverable error messages,
rather I expect to be able to _recover_ from errors without drama.

At present our `get_token/1` function is only following the "happy path":
https://github.com/dwyl/elixir-auth-google/blob/687fba552db8b5de2d353d42f77e2f04d9d428f9/lib/elixir_auth_google.ex#L18-L29

The callback function is `parse_body_response/1` which does not handle the `{:error, err}`

https://github.com/dwyl/elixir-auth-google/blob/687fba552db8b5de2d353d42f77e2f04d9d428f9/lib/elixir_auth_google.ex#L38-L45

This is _fine_ during MVP because as early ["dogfooding"](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) users we are _tolerant_ of the failure/errors.
But as soon as we _ship_ and show the MVP to (_friendly_) alpha test users, we need to have this done.

# Todo:

+ [ ] Research and document the various failure conditions and HTTP status codes
+ [ ] Add failure `case` statement to handle all the error conditions.
+ [ ] Update the `template` to ensure that error conditions are displayed in a friendly way.
+ [ ] Update instructions in `README.md` >  How? section to inform people about error scenarios.
+ [ ] Re-publish the hex.pm package with the error handling.

We do not need to handle the failures _before_ we ship our MVP, let's come back to this in Sprint 5+

**Comment by nelsonic** [comment]
```
[error] #PID<0.497.0> running AppWeb.Endpoint (connection #PID<0.490.0>, stream id 3) terminated
Server: localhost:4000 (http)
Request: GET /google/auth/callback?code=4/twGsqNPV6nd65fm069c2yC5ksEcPfXRRABiyqEEWdFjoGfmvQeUzwCbQR8SR01GSQxrzCmuvapr3hJdBedef__g&scope=email+profile+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email&authuser=0&session_state=45922e413dafb7369d0ceee57fbdadbab97c92fd..fcec&prompt=none
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function App.Ctx.Person.fetch/2 is undefined (App.Ctx.Person does not implement the Access behaviour)
        (app) App.Ctx.Person.fetch(%App.Ctx.Person{__meta__: #Ecto.Schema.Metadata<:built, "people">, email: nil, email_hash: nil, familyName: nil, givenName: nil, id: nil, inserted_at: nil, key_id: nil, locale: nil, password_hash: nil, picture: nil, sessions: #Ecto.Association.NotLoaded<association :sessions is not loaded>, status: nil, tag: nil, updated_at: nil, username: nil, username_hash: nil}, "email")
        (elixir) lib/access.ex:267: Access.get/3
        (app) lib/app_web/controllers/google_auth_controller.ex:65: AppWeb.GoogleAuthController.transform_profile_data_to_person/1
        (app) lib/app/ctx/person.ex:31: App.Ctx.Person.google_changeset/2
        (app) lib/app/ctx.ex:261: App.Ctx.create_google_person/1
        (app) lib/app_web/controllers/google_auth_controller.ex:14: AppWeb.GoogleAuthController.index/2
        (app) lib/app_web/controllers/google_auth_controller.ex:1: AppWeb.GoogleAuthController.action/2
        (app) lib/app_web/controllers/google_auth_controller.ex:1: AppWeb.GoogleAuthController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (app) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
        (app) lib/plug/debugger.ex:122: AppWeb.Endpoint."call (overridable 3)"/2
        (app) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /Users/n/code/app-mvp-phoenix/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/n/code/app-mvp-phoenix/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /Users/n/code/app-mvp-phoenix/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by ndrean** [comment]
All errors are 400;401 and 404 depending on the bad input.
You can consider this possible solution:

```elixir
def parse_status(request) do
    case request do
      {:ok, %{status_code: 200} = response} ->
        parse_body_response({:ok, response})
      {:ok, _} -> 
        {:error, :bad_input}

      or more verbose: 
      {:ok, %{status_code: 404}} ->
        {:error, :wrong_url}

      {:ok, %{status_code: 401}} ->
        {:error, :unauthorized_with_bad_secret}

      {:ok, %{status_code: 400}} ->
        {:error, :bad_code}
    end
  end
````
and use it: (`get_token` refactored to `get_profile` to expose only one function)

```elixir
def get_profile(code, conn) do
    Jason.encode!(%{
      client_id: google_client_id(),
      client_secret: google_client_secret(),
      redirect_uri: generate_redirect_uri(conn),
      grant_type: "authorization_code",
      code: code
    })
    |> then(fn body ->
      inject_poison().post(@google_token_url, body)
      |> parse_status()
    end)
    |> then(fn {status, response} ->
      case {status, response} do
        {:error, response} ->
          {:error, response}

        {:ok, response} ->
          get_user_profile(response.access_token)
      end
    end)
  end

def get_user_profile(access_token) do
    access_token
    |> encode()
    |>then(fn params ->
      (@google_user_profile <> "?" <> params)
      |> inject_poison().get()
      |> parse_status()
    end)
  end

  defp encode(token), do: URI.encode_query(%{access_token: token}, :rfc3986)
```
