### ISSUE TITLE
Detect Host URL on Localhost vs. Production

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#17]
As noted by @SimonLab in https://github.com/dwyl/app/issues/247#issuecomment-560470000 we are currently _hard_-coding the **`host`** (_domain_) for the Callback URL in the consuming project's `config.exs` e.g:
```
google_redirect_uri: "http://localhost:4000/google/auth/callback"
```
[dwyl/app-mvp-phoenix/config/config.exs#L33](https://github.com/dwyl/app-mvp-phoenix/blob/5e664187e8d46b15bce861820576f6f6547a5ef2/config/config.exs#L33)

This is undesirable because:
**a)** it forces the developer _using_ the package to add another configuration parameter and
**b)** they have to remember to define it _again_ when they ship to production ... 

We can _eliminate_ this effort entirely with a little helper function. 💡 
We want our package to be as "turn key" as possible, and that means having ["sensible defaults"](https://en.wikipedia.org/wiki/Convention_over_configuration) and functions that detect environment. We only want to require people to have the _bare minimum_ of configuration and the essential environment variables for the Google API. 

# Todo

+ [x] Update the `ElixirAuthGoogle.generate_oauth_url()` function to accept a `conn` parameter
+ [x] Detect the "base" url from the `conn` and return the appropriate full url
+ [x] on `localhost` it should be `http://localhost:4000/etc`
+ [ ] on `productoin` it should be `https://yourdomain.com/etc`

We don't need `ConnCase` to achieve this, we can _mock_ the `conn` with the data we need.

**Comment by nelsonic** [comment]
#18 merged. 👍
