### ISSUE TITLE
Update version of HTTPoison and Poison (mix.exs > deps) to 1.8 and 5.0

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#44]
We recently updated the version of `httpoison` in `elixir-auth-github`: https://github.com/dwyl/elixir-auth-github/pull/53
Which means there is a  Hex dependency resolution failure if we attempt to install the _latest_ version for one project but not the other ...

# Todo

+ [ ] Update `httpoison` to `1.8.0` https://hex.pm/packages/httpoison
+ [ ] Update `poison` to `5.0.0` https://hex.pm/packages/poison
+ [ ] Run tests
+ [ ] Create Pull Request
+ [ ] Publish new version of package `1.4.1` > `1.5.0`

**Comment by nelsonic** [comment]
Knew I had done this: https://github.com/dwyl/elixir-auth-google/pull/43 ✅ (_thanks Nelson from the Passed!_)

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/elixir-auth-google/issues/45
