### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-google#45]
Update the library's dependencies and use Elixir 1.12.3
see also https://github.com/dwyl/elixir-auth-google/pull/40#issuecomment-934476597

# Todo

+ [x] Update `httpoison` to `1.8.0` https://hex.pm/packages/httpoison #43 
+ [x] Update `poison` to `5.0.0` https://hex.pm/packages/poison
+ [x] Update `elixir` version in `mix.exs`
+ [x] Update `elixir` & `OTP` version in `.travis.yml`
+ [x] Run tests (both on `localhost` and Travis-CI)
+ [x] Create Pull Request
+ [x] Publish new version of package `1.4.1` > `1.5.0`

**Comment by nelsonic** [comment]
At least `httpoison` is up-to-date: https://github.com/dwyl/elixir-auth-google/pull/43/files

**Comment by SimonLab** [comment]
@nelsonic PR ready: #46

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/elixir_auth_google/1.5.0 📦

**Comment by nelsonic** [comment]
Closing as complete. ✅
