### ISSUE TITLE
Bug: `get_baseurl_from_conn/1` fails on `Fly.io`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-google#94]
Don't know why, but we're having trouble with `ElixirAuthGoogle.generate_oauth_url(conn)` on our `Calendar` app: https://github.com/dwyl/calendar/issues/38
We've identified that the `conn` on Fly.io is actually reporting `port: 80` and `scheme: :http` 
`get_baseurl_from_conn/1` is setting the scheme to `http` instead of `https` which means that Google Auth _Fails_ with the `Error 400: redirect_uri_mismatch` error. 😢 

I think we can check for the presence of the `req_headers -> x-forwarded-proto`  which is set to `"https"`
Just need to write a test for this ...

# Todo

+ [x] Create a test for  `{"x-forwarded-proto", "https"}`
+ [x] Add code to check for it at the _top_ of `get_baseurl_from_conn/1`
+ [x] Make sure nothing `else` breaks!
+ [x] Publish new version of the package to test in `calendar` App.

**Comment by nelsonic** [comment]
Test:
```elixir
  test "get_baseurl_from_conn(conn) x-forwarded-proto header for https #94" do
    conn = %{
      host: "gcal.fly.dev",
      port: 80,
      scheme: :http,
      req_headers: %{
        "x-forwarded-proto" => "https"
      }
    }

    assert ElixirAuthGoogle.get_baseurl_from_conn(conn) == "https://gcal.fly.dev"
  end
```

**Comment by nelsonic** [comment]
Getting on this _now_ cause I _really_ want to fix https://github.com/dwyl/calendar/issues/38

**Comment by nelsonic** [comment]
@jtormey thanks for commenting and sharing your experience. 
are you deployed to Fly.io?
No reason for _not_ using `Endpoint`. We just didn't have a _functional_ way of doing that.
Can we read the `Endpoint` from the context of a `Controller`?

Looks like it: https://stackoverflow.com/questions/40243229/how-to-get-the-current-base-domain-of-a-phoenix-app

```elixir
MyAppWeb.Endpoint.url()
# => "http://localhost:4000"
```

Ok, I don't really see a situation where this package will be used outside of a `Phoenix` App ... 💭 
So maybe we can shift to using this method to get the `base_url` ...

**Comment by jtormey** [comment]
Yes! I'm deployed to Fly.

That's a good point, relying on Endpoint would limit use of this library to Phoenix. Maybe would be best to derive from `conn` by default, with a configuration option where `Endpoint.url()` can be set as the base URL to use.

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/elixir-auth-google/pull/95

**Comment by SimonLab** [comment]
@nelsonic I'm trying to understand this issue, are you sure it's an issue linked to this package and not a configuration problem on the [calendar](https://github.com/dwyl/calendar) application (something similar to https://github.com/dwyl/phoenix-liveview-chat-example/pull/111) or a Fly.io issue?

I'm wondering why the google auth is working on the mvp application and not on the calendar.
Could it be linked to https://github.com/dwyl/calendar/issues/37 ?

I think I'm missing something so I'll try to reproduce this error on my side to understand the cause of this bug.

**Comment by nelsonic** [comment]
You should have access to https://fly.io/dashboard/dwyl-calendar if you want to debug. 🔍 
But ultimately this is what I think is the problem. 💭

**Comment by SimonLab** [comment]
Thanks for the explanation https://github.com/dwyl/elixir-auth-google/issues/94#issuecomment-1551085786
It helps me understand a bit better what's going on.
I'll have to look at it in more detail to understand it fully

**Comment by nelsonic** [comment]
Just tried to remove the `scheme: "https"` from [config/runtime.exs#L55](https://github.com/dwyl/calendar/blob/b6aacdc39d6a0ce0ac44d037785ba39c75531c41/config/runtime.exs#L55)

Deployed to Fly.io and still get the same error:

<img width="716" alt="image" src="https://github.com/dwyl/elixir-auth-google/assets/194400/0441f08a-2633-4387-adb9-229d0eb4d8b0">

So I'm thinking the only way to get around this is to explicitly read the `"x-forwarded-proto"` on Fly.io
***OR*** follow @jtormey's suggestion and allow people to pass in the `App.Endpoint.url()` 
Which looks like a far more robust way of doing this ... https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#c:url/0

**Comment by nelsonic** [comment]
Ok. this one is "fixed" by passing in the `Endpoint.url()` to `ElixirAuthGoogle.generate_oauth_url` ...
But now we have a different (related) issue: 

<img width="726" alt="image" src="https://github.com/dwyl/elixir-auth-google/assets/194400/4df9b4c7-2e58-4b36-8c19-2108d0c67a76">

https://fly.io/apps/gcal/monitoring
<img width="1626" alt="image" src="https://github.com/dwyl/elixir-auth-google/assets/194400/bed36f3f-784b-4f88-8e08-006e5ff71757">


In the `CalWeb.GoogleAuthController` [`/lib/cal_web/controllers/google_auth_controller.ex#L8`](https://github.com/dwyl/calendar/blob/b6aacdc39d6a0ce0ac44d037785ba39c75531c41/lib/cal_web/controllers/google_auth_controller.ex#L8) we call: 
```elixir
...
  {:ok, token} = ElixirAuthGoogle.get_token(code, conn)
  
  conn
  |> put_flash(:token, token)
  |> redirect(to: ~p"/app")
end
```

i.e. the `get_baseurl_from_conn/1` is still being invoked with `conn` by: 

https://github.com/dwyl/elixir-auth-google/blob/efba82a0ea88e9738547e837412e1baf7c352c46/lib/elixir_auth_google.ex#L95-L108

`L101` being the issue ... 🙄 

We _could_ create a new version of the `get_token/2` function ... 💭

**Comment by nelsonic** [comment]
Was quick to add so I just added it to the PR: #95 ✅

**Comment by nelsonic** [comment]
Published the new version of the `elixir_auth_google` package to Hex.pm: 

And used it in `Calendar`: https://gcal.fly.dev/

<img width="1468" alt="gcal-working-on-fly io" src="https://github.com/dwyl/calendar/assets/194400/ba23a5df-6a24-4177-9a20-92b5e7f139ad">

This is all working as expected now. ✅

**Comment by nelsonic** [comment]
Fixed. Closing. 👌

**Comment by odavidbrito** [comment]
Thanks for this update! Priceless!

I struggled a bit with the changes needed to make it work from the version in the readme.md (newbie here), so for posterity if someone bumps with the same issue.
Things to do so the redirect_url is https (and not http) in Fly.io and allows the Google app to be published (cant have http in there to be published, adding http redirect url to Google app was my workaround before finding this fix)

1. Increase the "elixir_auth_google" version in mix.exs:
![image](https://github.com/dwyl/elixir-auth-google/assets/14939970/3e926a10-d77f-4ec8-843e-7e2a13420234)

2. Replace "conn" with the Endpoint.url in the  GoogleAuthController:
![image](https://github.com/dwyl/elixir-auth-google/assets/14939970/ea29ba78-c45d-49b7-b9ec-38160fbfd5ed)

3. And the same in the PageController:
![image](https://github.com/dwyl/elixir-auth-google/assets/14939970/7eea8b71-0f7e-4ac0-b8b2-fffc367d06fa)

My app was named Google so adapt [Google]Web as needed so it gets the endpoint correctly.

Thanks for the work on these great demos (they are a perfect way to learn isolated things that I need for my app, and from scratch to deploy)  and fixes!
